# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/websites/HeimdallGI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/websites/HeimdallGI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/websites/HeimdallGI/CMakeFiles /var/websites/HeimdallGI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/websites/HeimdallGI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app.hgi

# Build rule for target.
app.hgi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app.hgi
.PHONY : app.hgi

# fast build rule for target.
app.hgi/fast:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/build
.PHONY : app.hgi/fast

#=============================================================================
# Target rules for targets named app.hgi_automoc

# Build rule for target.
app.hgi_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app.hgi_automoc
.PHONY : app.hgi_automoc

# fast build rule for target.
app.hgi_automoc/fast:
	$(MAKE) -f CMakeFiles/app.hgi_automoc.dir/build.make CMakeFiles/app.hgi_automoc.dir/build
.PHONY : app.hgi_automoc/fast

Abstract/Endpoint.o: Abstract/Endpoint.cpp.o
.PHONY : Abstract/Endpoint.o

# target to build an object file
Abstract/Endpoint.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/Endpoint.cpp.o
.PHONY : Abstract/Endpoint.cpp.o

Abstract/Endpoint.i: Abstract/Endpoint.cpp.i
.PHONY : Abstract/Endpoint.i

# target to preprocess a source file
Abstract/Endpoint.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/Endpoint.cpp.i
.PHONY : Abstract/Endpoint.cpp.i

Abstract/Endpoint.s: Abstract/Endpoint.cpp.s
.PHONY : Abstract/Endpoint.s

# target to generate assembly for a file
Abstract/Endpoint.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/Endpoint.cpp.s
.PHONY : Abstract/Endpoint.cpp.s

Abstract/PgModel.o: Abstract/PgModel.cpp.o
.PHONY : Abstract/PgModel.o

# target to build an object file
Abstract/PgModel.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/PgModel.cpp.o
.PHONY : Abstract/PgModel.cpp.o

Abstract/PgModel.i: Abstract/PgModel.cpp.i
.PHONY : Abstract/PgModel.i

# target to preprocess a source file
Abstract/PgModel.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/PgModel.cpp.i
.PHONY : Abstract/PgModel.cpp.i

Abstract/PgModel.s: Abstract/PgModel.cpp.s
.PHONY : Abstract/PgModel.s

# target to generate assembly for a file
Abstract/PgModel.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Abstract/PgModel.cpp.s
.PHONY : Abstract/PgModel.cpp.s

CGI.o: CGI.cpp.o
.PHONY : CGI.o

# target to build an object file
CGI.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/CGI.cpp.o
.PHONY : CGI.cpp.o

CGI.i: CGI.cpp.i
.PHONY : CGI.i

# target to preprocess a source file
CGI.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/CGI.cpp.i
.PHONY : CGI.cpp.i

CGI.s: CGI.cpp.s
.PHONY : CGI.s

# target to generate assembly for a file
CGI.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/CGI.cpp.s
.PHONY : CGI.cpp.s

Configuration.o: Configuration.cpp.o
.PHONY : Configuration.o

# target to build an object file
Configuration.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Configuration.cpp.o
.PHONY : Configuration.cpp.o

Configuration.i: Configuration.cpp.i
.PHONY : Configuration.i

# target to preprocess a source file
Configuration.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Configuration.cpp.i
.PHONY : Configuration.cpp.i

Configuration.s: Configuration.cpp.s
.PHONY : Configuration.s

# target to generate assembly for a file
Configuration.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Configuration.cpp.s
.PHONY : Configuration.cpp.s

DBI.o: DBI.cpp.o
.PHONY : DBI.o

# target to build an object file
DBI.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/DBI.cpp.o
.PHONY : DBI.cpp.o

DBI.i: DBI.cpp.i
.PHONY : DBI.i

# target to preprocess a source file
DBI.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/DBI.cpp.i
.PHONY : DBI.cpp.i

DBI.s: DBI.cpp.s
.PHONY : DBI.s

# target to generate assembly for a file
DBI.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/DBI.cpp.s
.PHONY : DBI.cpp.s

ErrorController.o: ErrorController.cpp.o
.PHONY : ErrorController.o

# target to build an object file
ErrorController.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/ErrorController.cpp.o
.PHONY : ErrorController.cpp.o

ErrorController.i: ErrorController.cpp.i
.PHONY : ErrorController.i

# target to preprocess a source file
ErrorController.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/ErrorController.cpp.i
.PHONY : ErrorController.cpp.i

ErrorController.s: ErrorController.cpp.s
.PHONY : ErrorController.s

# target to generate assembly for a file
ErrorController.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/ErrorController.cpp.s
.PHONY : ErrorController.cpp.s

HTML.o: HTML.cpp.o
.PHONY : HTML.o

# target to build an object file
HTML.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/HTML.cpp.o
.PHONY : HTML.cpp.o

HTML.i: HTML.cpp.i
.PHONY : HTML.i

# target to preprocess a source file
HTML.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/HTML.cpp.i
.PHONY : HTML.cpp.i

HTML.s: HTML.cpp.s
.PHONY : HTML.s

# target to generate assembly for a file
HTML.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/HTML.cpp.s
.PHONY : HTML.cpp.s

Log.o: Log.cpp.o
.PHONY : Log.o

# target to build an object file
Log.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Log.cpp.o
.PHONY : Log.cpp.o

Log.i: Log.cpp.i
.PHONY : Log.i

# target to preprocess a source file
Log.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Log.cpp.i
.PHONY : Log.cpp.i

Log.s: Log.cpp.s
.PHONY : Log.s

# target to generate assembly for a file
Log.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Log.cpp.s
.PHONY : Log.cpp.s

Pool/Database.o: Pool/Database.cpp.o
.PHONY : Pool/Database.o

# target to build an object file
Pool/Database.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Pool/Database.cpp.o
.PHONY : Pool/Database.cpp.o

Pool/Database.i: Pool/Database.cpp.i
.PHONY : Pool/Database.i

# target to preprocess a source file
Pool/Database.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Pool/Database.cpp.i
.PHONY : Pool/Database.cpp.i

Pool/Database.s: Pool/Database.cpp.s
.PHONY : Pool/Database.s

# target to generate assembly for a file
Pool/Database.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Pool/Database.cpp.s
.PHONY : Pool/Database.cpp.s

Router.o: Router.cpp.o
.PHONY : Router.o

# target to build an object file
Router.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Router.cpp.o
.PHONY : Router.cpp.o

Router.i: Router.cpp.i
.PHONY : Router.i

# target to preprocess a source file
Router.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Router.cpp.i
.PHONY : Router.cpp.i

Router.s: Router.cpp.s
.PHONY : Router.s

# target to generate assembly for a file
Router.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Router.cpp.s
.PHONY : Router.cpp.s

Template.o: Template.cpp.o
.PHONY : Template.o

# target to build an object file
Template.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Template.cpp.o
.PHONY : Template.cpp.o

Template.i: Template.cpp.i
.PHONY : Template.i

# target to preprocess a source file
Template.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Template.cpp.i
.PHONY : Template.cpp.i

Template.s: Template.cpp.s
.PHONY : Template.s

# target to generate assembly for a file
Template.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/Template.cpp.s
.PHONY : Template.cpp.s

View.o: View.cpp.o
.PHONY : View.o

# target to build an object file
View.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/View.cpp.o
.PHONY : View.cpp.o

View.i: View.cpp.i
.PHONY : View.i

# target to preprocess a source file
View.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/View.cpp.i
.PHONY : View.cpp.i

View.s: View.cpp.s
.PHONY : View.s

# target to generate assembly for a file
View.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/View.cpp.s
.PHONY : View.cpp.s

app.hgi_automoc.o: app.hgi_automoc.cpp.o
.PHONY : app.hgi_automoc.o

# target to build an object file
app.hgi_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/app.hgi_automoc.cpp.o
.PHONY : app.hgi_automoc.cpp.o

app.hgi_automoc.i: app.hgi_automoc.cpp.i
.PHONY : app.hgi_automoc.i

# target to preprocess a source file
app.hgi_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/app.hgi_automoc.cpp.i
.PHONY : app.hgi_automoc.cpp.i

app.hgi_automoc.s: app.hgi_automoc.cpp.s
.PHONY : app.hgi_automoc.s

# target to generate assembly for a file
app.hgi_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/app.hgi_automoc.cpp.s
.PHONY : app.hgi_automoc.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/app.hgi.dir/build.make CMakeFiles/app.hgi.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app.hgi_automoc"
	@echo "... app.hgi"
	@echo "... Abstract/Endpoint.o"
	@echo "... Abstract/Endpoint.i"
	@echo "... Abstract/Endpoint.s"
	@echo "... Abstract/PgModel.o"
	@echo "... Abstract/PgModel.i"
	@echo "... Abstract/PgModel.s"
	@echo "... CGI.o"
	@echo "... CGI.i"
	@echo "... CGI.s"
	@echo "... Configuration.o"
	@echo "... Configuration.i"
	@echo "... Configuration.s"
	@echo "... DBI.o"
	@echo "... DBI.i"
	@echo "... DBI.s"
	@echo "... ErrorController.o"
	@echo "... ErrorController.i"
	@echo "... ErrorController.s"
	@echo "... HTML.o"
	@echo "... HTML.i"
	@echo "... HTML.s"
	@echo "... Log.o"
	@echo "... Log.i"
	@echo "... Log.s"
	@echo "... Pool/Database.o"
	@echo "... Pool/Database.i"
	@echo "... Pool/Database.s"
	@echo "... Router.o"
	@echo "... Router.i"
	@echo "... Router.s"
	@echo "... Template.o"
	@echo "... Template.i"
	@echo "... Template.s"
	@echo "... View.o"
	@echo "... View.i"
	@echo "... View.s"
	@echo "... app.hgi_automoc.o"
	@echo "... app.hgi_automoc.i"
	@echo "... app.hgi_automoc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

